#!/bin/bash
# Build ProxyToggle.app. Usage: ./build.sh [install-dir]   (default: ~/Applications)
set -euo pipefail
cd "$(dirname "$0")"

APP_NAME="ProxyToggle"
DEST="${1:-$HOME/Applications}"
APP="$DEST/$APP_NAME.app"

if ! command -v swiftc >/dev/null 2>&1; then
  echo "swiftc not found. Install the Xcode command line tools first:" >&2
  echo "  xcode-select --install" >&2
  exit 1
fi

# scripts/proxyctl is the single source of truth for the privileged helper;
# embed it into the binary as a Swift raw string literal.
{
  echo '// GENERATED by build.sh from scripts/proxyctl — do not edit.'
  echo 'let helperSource = #"""'
  cat scripts/proxyctl
  echo '"""#'
} > Sources/HelperSource.swift

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"

swiftc -O -o "$APP/Contents/MacOS/$APP_NAME" \
  Sources/*.swift \
  -framework AppKit -framework SystemConfiguration -framework ServiceManagement

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>ProxyToggle</string>
  <key>CFBundleDisplayName</key><string>ProxyToggle</string>
  <key>CFBundleExecutable</key><string>ProxyToggle</string>
  <key>CFBundleIdentifier</key><string>local.proxytoggle</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
  <key>LSUIElement</key><true/>
  <key>NSAppleEventsUsageDescription</key>
  <string>初回のみ、プロキシ切り替え用の特権ヘルパーを設置するために管理者認証を行います。</string>
</dict>
</plist>
PLIST

# Ad-hoc signature: keeps a stable identity for login items and TCC on this Mac.
codesign --force --sign - "$APP"

echo "built: $APP"
